repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
      language_version: python3
      src: "./src"

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1  # Replace with the desired mypy version
    hooks:
    -   id: mypy
        files: ^src/
        args: [--ignore-missing-imports, --disallow-untyped-defs]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
